server:
  port: 8081
spring:
  rabbitmq:
    request:
      host: localhost
      port: 5672
      username: admin
      password: admin
      exchange:
        subscriber: ex.subscriber.springboot-rabbitmq-class
      routing-key:
        subscriber: rk.subscriber.springboot-rabbitmq-class
      deadletter:
        subscriber: dl.subscriber.springboot-rabbitmq-class
      parking-lot:
        subscriber: pl.subscriber.springboot-rabbitmq-class
